c404_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp import views as a_view
from django.conf import settings
from django.conf.urls.static import static
from firstapp.views import(
    search_user,
    login,
    signup,
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('firstapp/', a_view.index, name='index'),
    path('firstapp/login/', login, name='login'),
    path('firstapp/signup/', signup, name='signup'),
    path('firstapp/index/', a_view.index, name='index'),
    path('firstapp/homepage/', a_view.homepage, name='home'),
    path('firstapp/search/', search_user, name = "search"),
    path('firstapp/',include('firstapp.urls',namespace = 'account')),
    path('friend/', include('friend.urls', namespace='friend')),

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

firstapp/urls.py
from django.urls import path
from . import views
from firstapp.views import(
	account_view)
app_name = 'firstapp'
urlpatterns = [
	path('<int:user_id>/',account_view,name = "view"),
	path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('homepage/', views.homepage, name='home'),
    path('author/<str:user_id>/posts/<int:post_id>',views.post,name='post'),
    path('author/<str:user_id>/posts/', views.allposts, name='allposts'),
    # path('author/<int:user_id>/inbox', views.inbox, name='inbox'),
    path('author/<str:user_id>/posts/<int:post_id>/likes/', views.postlikes, name='postlikes'),
    path('author/<str:user_id>/posts/<int:post_id>/likepost/', views.likepost, name='likepost'),
    path('author/<str:user_id>/posts/<int:post_id>/likecomment/', views.like_comment, name='likecomment'),
    path('author/<str:user_id>/liked/', views.liked, name='liked'),
    path('author/<str:user_id>', views.account, name='account'),
    path('author/<str:user_id>/', views.account, name='account'),

    path('author/<str:user_id>/posts/<int:post_id>/commentpost/',views.commentpost,name='commentpost'),
    path('author/<str:user_id>/posts/<int:post_id>/comments/',views.viewComments,name='viewComments'),
    path('author/<str:user_id>/posts/<int:post_id>/comments',views.viewComments,name='viewComments'),

    path('posts/', views.publicposts,name='publicposts'),
    path('author/<str:user_id>/inbox', views.inbox,name='inbox'),
    path('author/<str:user_id>/inbox/', views.inbox,name='inbox'),
    path('like/',views.likeAHomePagePost,name="likeAPost"),
    path('comment/',views.commentAHomePagePost,name="commentAPost"),
    path('author/<str:user_id>/posts/<int:post_id>/comments/<str:comment_id>',views.viewComment,name='viewComment'),
    path('author/<str:user_id>/posts/<int:post_id>/comment',views.makeComment,name='makeComment'),
    path('author/<str:user_id>/posts/<int:post_id>/comment/',views.makeComment,name='makeComment'),
    path('publicshare/',views.sharePublicPost),
    path('post-tests/',views.run_post_tests)

]

friend/urls.py
from django.urls import path

from friend.views import(
	send_friend_request,
	request_view,
	accept_friend_request,
	friends_list_view,
	following_list_view,
	follower_list_view,
	send_following_request
)

app_name = 'friend'

urlpatterns = [
	path('list/<user_id>', friends_list_view, name='list'),
	path('followinglist/<user_id>', following_list_view, name='followinglist'),
	path('followerlist/<user_id>', follower_list_view, name='followerlist'),
    path('friend_request/', send_friend_request, name='friend-request'),
    path('friend_requests/<user_id>/', request_view, name='friend-requests'),
    path('friend_request_accept/<friend_request_id>/', accept_friend_request, name='friend-request-accept'),
    path('follow_request/<following_request_id>/', send_following_request, name='send_following_request'),

    ]

firstapp/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
from django.conf import settings


# Create your models here.
class Author(models.Model):
    type = "author"
    username = models.CharField(max_length=20, null=False)
    github = models.URLField(blank=True) # Github link
    github_username = models.TextField(max_length=20,blank=True)
    host = models.TextField(max_length=500, blank=True)
    authorized = models.BooleanField(default=True) # Whether they are allowed to log in
    userid = models.PositiveIntegerField(default=0,null=True) # Good for finding their URL in posts
    email = models.EmailField(default="example@gmail.com")
    name = models.CharField(max_length=20,default="testname") # First and last name
    consistent_id = models.TextField(primary_key=True,blank=True)
    api_token = models.TextField(max_length=50,blank=True)

    def __str__(self):
        return self.username

class Setting(models.Model):
  # Contains variables for global settings
  # Should be a singleton setting in Admin. If not set/initialized in admin, error is thrown when trying to sign up.
  usersneedauthentication = models.BooleanField(default=False)
  def __str__(self):
    return "Settings"
class PublicImage(models.Model): # Host images to a folder in server. Accessible in server admin
  # Followed tutorial by Will Vincent at 2021-03-05 at https://learndjango.com/tutorials/django-file-and-image-uploads-tutorial
  title = models.TextField()
  image = models.ImageField(upload_to='images/')
  def __str__(self):
    return self.title

class Post(models.Model):
  type = "post"
  id = models.TextField(blank=True)
  post_id = models.PositiveIntegerField(primary_key=True, default=0)
  user_id = models.TextField(blank=True)
  title = models.CharField(max_length=40,default="")
  description = models.CharField(max_length=40,default="")
  markdown = models.BooleanField(default=False)
  content = models.TextField(max_length=500,blank=True)
  image = models.BinaryField(default=b"")
  privfriends = models.BooleanField(default = False)
  unlisted = models.BooleanField(default = False)
  published = models.CharField(max_length=50,default="")
  source = models.TextField(blank=True)
  origin = models.TextField(blank=True)

class Author_Privacy(models.Model):
  type = "author_privacy"
  post_id = models.PositiveIntegerField(default=0)
  user_id = models.TextField(max_length=20,blank=True)

class Category(models.Model):
  type = "category"
  post_id = models.PositiveIntegerField(default=0)
  tag = models.TextField(max_length=20,blank=True) # The actual content of the category

class Comment(models.Model):
    # post = models.ForeignKey(Post, on_delete=models.CASCADE)
    post_id = models.TextField(blank=True, null=False)
    comment_id = models.TextField(primary_key=True,null=False)
    from_user = models.TextField(blank=True, null=True)
    to_user = models.TextField(blank=True, null=True)
    comment_text = models.TextField(null=False)
    published = models.CharField(max_length=50,default="")
    
    def __str__(self):
        return self.comment_text

class Like(models.Model):
  like_id = models.PositiveIntegerField(primary_key=True, blank=True, null=False)
  from_user = models.TextField()
  to_user = models.TextField(max_length=500,blank=True)
  object = models.TextField()

class Node(models.Model):
  hostserver = models.URLField(null=False)
  authusername = models.TextField(null=False)
  authpassword = models.TextField(null=False)
  def __str__(self):
    return self.hostserver
  
class Inbox(models.Model):
  type = models.TextField()
  author = models.TextField()
  items = models.JSONField(default=list)

firstapp/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.http import HttpResponseNotFound, HttpResponseForbidden, HttpResponseBadRequest
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .form import UserForm, CommentForm
# from .form import UserForm
from django.urls import reverse
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import QueryDict
from django.utils.datastructures import MultiValueDictKeyError
from django.db import connection
import sqlite3
import os
from random import randrange as rand
from datetime import datetime
import json
from django.conf import settings
from markdown import Markdown as Md
from django.core.mail import send_mail
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from .permissions import EditPermission
from rest_framework.authentication import BasicAuthentication, SessionAuthentication, TokenAuthentication
from rest_framework.authtoken.models import Token
from friend.request_status import RequestStatus
from friend.follow_status import FollowStatus
from friend.models import FriendList, FriendRequest,FriendShip,FollowingList,Follow
from friend.is_friend import get_friend_request_or_false
from friend.is_following import Following_Or_Not
from firstapp.models import Author, Post, Author_Privacy, Comment, Like, Category, Node, Setting, Inbox
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AnonymousUser
import uuid
import requests
import base64
from urllib.parse import urlparse
from html import escape
from .remote_friend import get_all_remote_user,get_all_remote_user_2
from django.contrib.auth.models import User
from django.core import serializers
from django.core.paginator import Paginator
from django.contrib.admin.views.decorators import staff_member_required
import subprocess
FILEPATH = os.path.dirname(os.path.abspath(__file__)) + "/"

ADD_QUERY = "INSERT INTO posts VALUES (?, ?, ?, ?, ?, ?, ?, ?);"
EDIT_QUERY = "UPDATE posts SET post_id=?, user_id=?, title=?, description=?, markdown=?, content=?, image=?, published=? WHERE post_id=? AND user_id =?;"

PRIV_ADD_QUERY = "INSERT INTO author_privacy VALUES (?,?);"
STR2BOOL = lambda x: bool(int(x))

# Create your views here.
def index(request):
    #if request.user.is_authenticated:
    return render(request, 'index.html')

#helper function for getting json author objects from our server's database
def get_our_author_object(host, author_uuid):
    print("entered get_our_author_object")
    try:
        url = "https://"+host+"/author/"+author_uuid
        print(url)
        r = requests.get(url)
        print("getting author succesfull")
        return r.json()
    except Exception as e:
        print(e)
        return HttpResponseNotFound("The account you requested does not exist\n")

def homepage(request):
    if request.user.is_authenticated:
        try:
            author = Author.objects.get(username=request.user)
            token = author.api_token
        except Author.DoesNotExist:
            return HttpResponseNotFound(f"In the homepage function, the user you requested does not exist!!{request.user}\n")
        if not author.authorized:
            messages.add_message(request,messages.INFO, 'Please wait to be authenticated by a server admin.')
            return HttpResponseRedirect(reverse('login'))
        user_id,author_uuid = author.userid,author.consistent_id
        ourURL = f"https://"+request.META['HTTP_HOST']+"/posts" # change this to https in heroku, http in local server
        print(f"\n\n\n\n{ourURL}\n\n\n")
        ourRequest = requests.get(url=ourURL)
        print(f"\n\n{ourRequest}\n\n")
        ourData = ourRequest.json()
        # print(ourRequest)
        print("\n")



        # Get all public posts from another server, from the admin panel
        servers = Node.objects.all()
        theirData = []
        auth_user = ""
        auth_pass = ""
        for server in servers: # Iterate through each server, providing authentication if necessary
            try:
                postsRequest = requests.get(url=f"{server.hostserver}/posts", auth = (f"{server.authusername}",f"{server.authpassword}"))
                auth_user = server.authusername
                auth_pass = server.authpassword
                if postsRequest.status_code == 200:
                    theirData.extend(postsRequest.json())
                    #TODO find a way to pass in auth info with post json
            except Exception as e:
                print(f"Could not connect to {server.hostserver} becuase: {e} :(")
                continue
        # print(ourData)
        # print(theirData)
        return render(request, 'homepage.html', {'user_id':user_id,'author_uuid':author_uuid, 'our_server_posts':ourData,'other_server_posts':theirData,"author":author})
    
def signup(request):
    # Called when user accesses the signup page
    success = False
    if request.method == 'POST': # When a user wants to sign up, first validate:
        form = UserForm(request.POST) # A form consisting of username, password, email, and name
        if form.is_valid():
            user = form.save()
            new_username = form.cleaned_data.get('username')
            new_password = form.cleaned_data.get('password1')
            user = authenticate(username = new_username, password=new_password) # Attempt to authenticate user after using checks. Returns User object if succesful, else None
            auth_login(request, user) # Save user ID for further sessions
            #Token(user=user).save()
            #user.save()
            success = True
            # Check if UsersNeedAuthentication is True. If it is, redirect to login and set Authorized to False for that user
            # Else, let the use in the homepage, set Authorized to True
            try:
                settings = Setting.objects.get()
            except Setting.DoesNotExist:
                print("make a setting")
                settings = Setting(usersneedauthentication=False)
            needs_authentication = settings.usersneedauthentication
            # print(f"AUTHENTICATE ME https://{request.get_host()}")
            if needs_authentication: # If users need an OK from server admin, create the user, but set authorized to False, preventing them from logging in.
                user = Author.objects.create(host=f"https://{request.get_host()}",username=new_username,userid=request.user.id,\
                    authorized=False,email=form.cleaned_data['email'],\
                        name=f"{form.cleaned_data['first_name']} {form.cleaned_data['last_name']}",\
                            consistent_id=f"{uuid.uuid4().hex}",api_token = Token.objects.create(user=user))
                # If the flag, UsersNeedAuthentication is True, redirect to Login Page with message
                user.save()
                user_inbox = Inbox.objects.create(type="inbox", author=f"https://{request.get_host()}/author/{user.consistent_id}", items=[])
                user_inbox.save()
                messages.add_message(request,messages.INFO, 'Please wait to be authenticated by a server admin.')
                return HttpResponseRedirect(reverse('login'))
            # Else, let them in homepage.
            user = Author.objects.create(host=f"https://{request.get_host()}",username=new_username,\
                userid=request.user.id, authorized=True,email=form.cleaned_data['email'],\
                    name=f"{form.cleaned_data['first_name']} {form.cleaned_data['last_name']}",\
                        consistent_id=f"{uuid.uuid4().hex}",api_token = Token.objects.create(user=user))
            user_inbox = Inbox.objects.create(type="inbox", author=f"https://{request.get_host()}/author/{user.consistent_id}", items=[])
            
            return HttpResponseRedirect(reverse('home'))
        else:
            context = {'form':form}
            return render(request, 'signup.html', context)
    else:
        form = UserForm()
        context = {'form':form}
        return render(request, 'signup.html', context)

def login(request):
    if request.method == 'POST':
        new_username = request.POST.get('username')
        new_password = request.POST.get('password')

        # print(Author.objects.get(username=request.user))
        user = authenticate(username = new_username, password = new_password)
        if user is not None:
            # Check if Authorized. If so, proceed. Else, display an error message and redirect back to login page.

            try:
                author = Author.objects.get(username=new_username)
            except Author.DoesNotExist:
                messages.add_message(request,messages.INFO, f'This user, {new_username}, does not exist.')
                return HttpResponseRedirect(reverse('login'))
            authenticated = author.authorized
            if not authenticated:
                messages.add_message(request,messages.INFO, 'Please wait to be authenticated by a server admin.')
                return HttpResponseRedirect(reverse('login'))
            else:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('home'))
        else:
            print("Invalid account!")
            return HttpResponseRedirect(reverse('login'))
    else:
        form = AuthenticationForm()
        context = {'form':form}
        return render(request, 'login.html', context)

def validate_int(p,optional=[]):
    try:
        int(p["markdown"])
        for i in optional: int(i)
        return 1
    except ValueError: return 0

# escapes instances of <script> and </script> tags from content
def clean_script(content):

firstapp/templates/follower_list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
	
</style>

<div class="container">
	<div class="card p-2">

		{% if followers %}
		<div class="d-flex flex-row flex-wrap">
		{% for follower in followers %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<div >
				<a href="{% url 'account:view' user_id=follower.0.pk %}">
					<h4 class="card-title">{{follower.0.username}}</h4>
				</a>
			</div>
			
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if following.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							following 
						</p>
					</div>
				{% else %}
					{% if friend.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends 
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if friend.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No friends :(</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

{% endblock content %}

firstapp/templates/following_list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
	
</style>

<div class="container">
	<div class="card p-2">

		{% if followings %}
		<div class="d-flex flex-row flex-wrap">
		{% for following in followings %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<div >
				<a href="{% url 'account:view' user_id=following.0.pk %}">
					<h4 class="card-title">{{following.0.username}}</h4>
				</a>
			</div>
			
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if following.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							following 
						</p>
					</div>
				{% else %}
					{% if friend.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends 
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if friend.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No friends :(</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

{% endblock content %}

firstapp/templates/friend_list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
	
</style>

<div class="container">
	<div class="card p-2">

		{% if friends %}
		<div class="d-flex flex-row flex-wrap">
		{% for friend in friends %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'account:view' user_id=friend.0.pk %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{friend.0.profile_image.url}}" alt="">
				</div>
			</a>
			
			<div class="card-center px-2">
				<a class="profile-link" href="{% url 'account:view' user_id=friend.0.pk %}">
					<h4 class="card-title">{{friend.0.username|truncatechars:50}}</h4>
				</a>
				{% if friend.1 %}
				{% endif %}
				
			</div>
			
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if friend.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							Friends 
						</p>
						<span class="material-icons checkmark-icon m-auto pl-2">
						check_circle_outline
						</span>
					</div>
				{% else %}
					{% if friend.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends 
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if friend.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No friends :(</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

{% endblock content %}

firstapp/templates/friend_requests.html
{% extends 'index.html' %}
{% load static %}

{% block content %}


<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
</style>

<div class="container">
	<div class="card p-2">

		{% if friend_requests %}
		<div class="d-flex flex-row flex-wrap">
		{% for request in friend_requests %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'account:view' user_id=request.sender.id %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{request.sender.profile_image.url}}" alt="">
				</div>
			</a>
			<a class="profile-link" href="{% url 'account:view' user_id=request.sender.id %}">
				<div class="card-center px-2">
					<h4 class="card-title">{{request.sender.username}}</h4>
				</div>
			</a>
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
	  			<span id="id_cancel_{{request.sender.id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{request.id}}")'>cancel</span>
	  			<span id="id_confirm_{{request.sender.id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{request.id}}")'>check</span>
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No results</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

<script type="text/javascript">

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
</script>

{% include 'accept_friend_request.html' %}
{#% include 'friend/snippets/decline_friend_request.html' %#}


{% endblock content %}

firstapp/templates/likes.html
<!DOCTYPE html>
<html>
<head>
    {% include "sub_basic/header.html" %}

    {% csrf_token %}
</head>

<body>
    <p>{{num_likes}} likes on this post </p>
</body>

</html>

firstapp/templates/login.html
{% extends "index.html" %}
{% block content %}


<h1>User Login</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Login</button>
</form>
<p class="text-center">New user? Click<a href="/firstapp/signup"> here </a>to register

{% endblock %}

firstapp/templates/send_request.html
<script type="text/javascript">
	
	function sendFriendRequest(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'friend:friend-request' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				console.log("SUCCESS", data)

				if(data['response'] == "Friend request sent."){

					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	

</script>